# Intelligent Login Risk Analyzer  
## Notebook 04: Model Training

This notebook trains an anomaly detection model using the engineered features prepared in the previous notebook.

We use an unsupervised learning approach because real anomaly labels are usually limited in cybersecurity scenarios.

## Step 1: Import Required Libraries

We import the libraries required for loading the processed dataset and training the anomaly detection model.

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

## Step 2: Load Processed Feature Dataset

We load the feature-engineered dataset created in Notebook 03.

In [2]:
X = pd.read_csv('../outputs/processed_features.csv')
X.head()

   is_failed  is_night_login  ...  device_or_browser_Firefox  device_or_browser_Mobile
0          1               0  ...                      False                     False
1          1               1  ...                      False                     False
2          1               1  ...                       True                     False
3          0               0  ...                      False                     False
4          1               0  ...                      False                      True

[5 rows x 34 columns]

## Step 3: Review Feature Dataset Shape

This step confirms the number of rows and columns available for model training.

In [3]:
print("Feature dataset shape:", X.shape)

Feature dataset shape: (300, 34)

## Step 4: Initialize the Isolation Forest Model

Isolation Forest is an unsupervised anomaly detection algorithm that isolates unusual observations instead of learning from labeled attack data.

It is suitable for this project because:
- anomaly labels are not fully available
- suspicious login behavior is rare compared to normal behavior
- it works well for outlier detection tasks

In [4]:
model = IsolationForest(
    n_estimators=100,
    contamination=0.1,
    random_state=42
)

## Step 5: Train the Model

We fit the Isolation Forest model on the processed login features.

In [5]:
model.fit(X)

IsolationForest(contamination=0.1, random_state=42)

## Step 6: Generate Anomaly Predictions

The model returns:
- `1` for normal observations
- `-1` for anomalies

We store the predictions for further analysis.

In [6]:
predictions = model.predict(X)
predictions[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Step 7: Add Predictions to the Dataset

We attach the model predictions to the feature dataset for interpretation.

In [7]:
X['anomaly_prediction'] = predictions
X.head()

   is_failed  is_night_login  ...  device_or_browser_Mobile  anomaly_prediction
0          1               0  ...                     False                   1
1          1               1  ...                     False                   1
2          1               1  ...                     False                   1
3          0               0  ...                     False                   1
4          1               0  ...                      True                   1

[5 rows x 35 columns]

## Step 8: Count Normal vs Anomalous Records

This step shows how many records were classified as normal and how many were flagged as anomalies.

In [8]:
X['anomaly_prediction'].value_counts()

anomaly_prediction
 1    270
-1     30
Name: count, dtype: int64

## Step 9: Convert Predictions into Readable Labels

For better interpretation, we map the prediction values into human-readable classes.

In [9]:
X['anomaly_label'] = X['anomaly_prediction'].map({1: 'Normal', -1: 'Anomaly'})
X[['anomaly_prediction', 'anomaly_label']].head()

   anomaly_prediction anomaly_label
0                   1        Normal
1                   1        Normal
2                   1        Normal
3                   1        Normal
4                   1        Normal

## Step 10: Inspect Detected Anomalies

We filter the records predicted as anomalies to understand what the model is flagging.

In [10]:
anomalies = X[X['anomaly_label'] == 'Anomaly']
anomalies.head(10)

    is_failed  is_night_login  is_high_risk_location  ...  device_or_browser_Mobile  anomaly_prediction  anomaly_label
15          0               0                      0  ...                      True                  -1        Anomaly
22          0               1                      0  ...                     False                  -1        Anomaly
38          1               0                      0  ...                     False                  -1        Anomaly
51          0               0                      0  ...                     False                  -1        Anomaly
52          1               0                      1  ...                     False                  -1        Anomaly
53          0               1                      0  ...                     False                  -1        Anomaly
75          0               1                      1  ...                     False                  -1        Anomaly
77          1               0                      0  ...                     False                  -1        Anomaly
86          1               0                      0  ...                     False                  -1        Anomaly
91          0               0                      1  ...                      True                  -1        Anomaly

[10 rows x 36 columns]

## Additional Note

The anomaly predictions are model-based outlier signals, not confirmed attacks.

These outputs should be interpreted as suspicious records requiring further review, not as final proof of compromise.

## Step 11: Save Model Predictions

We save the prediction results for use in the evaluation notebook.

In [11]:
X.to_csv('../outputs/model_predictions.csv', index=False)

## Summary

In this notebook, we:
- loaded the processed feature dataset
- trained an Isolation Forest anomaly detection model
- generated anomaly predictions
- labeled records as normal or anomalous
- saved prediction results for further evaluation

This notebook establishes the first machine learning layer of the Intelligent Login Risk Analyzer.